name: Semgrep SAST Scan
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar Semgrep
        run: pip install semgrep
      - name: Executar análise con regras automáticas
        run: semgrep --config=auto . --output=semgrep-results.json
      # - name: Executar análisis con reglas personalizadas
      #   run: semgrep --config=semgrep-rules.yaml --json --output=semgrep-results.json
      - name: Mostrar resultados na saída de GitHub Actions
        run: cat semgrep-results.json
      - name: Gardar informe de Semgrep como artefacto
        uses: actions/upload-artifact@v6
        with:
          name: semgrep-report
          path: semgrep-results.json
